[bundle]
name           = "multi-role-pg"
version        = "0.1.0"
description    = "Postgres + Patroni + pgbouncer fleet bundle (demo)"
requires_bosun = "^0.1"
entry          = "manifests/main.star"

[bundle.inventory]
default_merge_strategy = "deep_map_replace_list"

[bundle.tags]
production = "Production cluster"
staging    = "Staging cluster"
